#!/bin/bash
# creator: Chance Garcia <chance@chancegarcia.com>
# twitter: chancegarcia

if [ ! -e /usr/bin/lsb_release ]; then
    echo "Unable to find lsb_release to check for ubuntu system."
    exit 1
fi

# todo use/parse lsb_release to verify ubuntu

if [ ! $# -eq 1 ]; then
    echo "Which version of PHP do you want to switch to?"
    echo "Your options are:"
    update-alternatives --list php | grep -oP "(\d\.\d+?)"
    exit 1
else
    if [[ $1 =~ [0-9]\.[0-9]+? ]]; then
        switch_to=$1
    else
        echo "Invalid version number"
        exit 1
    fi
fi

echo "Switch to PHP $switch_to"

switch_from=`php --version | grep -oP "PHP (\d\.\d+?)" | cut -d " " -f2`
echo "Switch from PHP $switch_from"
echo "This will require sudo privileges"

echo "Switching CLI"
sudo update-alternatives --set php /usr/bin/php$switch_to
# todo add phar, etc?

echo "Switching apache"
sudo a2dismod php$switch_from;
sudo a2enmod php$switch_to;

read -p "Activate new config 'sudo systemctl restart apache2' (y/N)?" yn
case $yn in
        [Yy]* ) sudo systemctl restart apache2; break;;
        [Nn]* ) exit;;
        * ) echo exit;;
    esac

echo "Switch to $switch_to is now complete"
php --version
